---
api:
  host: kargo.home.lab
  adminAccount:
    ## @param api.adminAccount.enabled Whether to enable the admin account.
    enabled: true
    ## @param api.adminAccount.passwordHash Bcrypt password hash for the admin account. A value **must** be provided for this field unless `api.secret.name` is specified.
    passwordHash: "$2y$10$6JOwwFWeY6gMvv4ARt6qD.Qq74hK08xzrsEH2aIrrX9WFn9fS1TQC"
    ## @param api.adminAccount.tokenSigningKey Key used to sign ID tokens (JWTs) for the admin account. It is suggested that you generate this using a password manager or a command like: `openssl rand -base64 29 | tr -d "=+/"`. A value **must** be provided for this field, unless `api.secret.name` is specified.
    tokenSigningKey: "I0LX5sM9dnXXCKVD5nfoKquxTIDJxV8YDpW9k5g"
    ## @param api.adminAccount.tokenTTL Specifies how long ID tokens for the admin account are valid. (i.e. The expiry will be the time of issue plus this duration.)
    tokenTTL: 24h
  tls:
    enabled: false
    terminatedUpstream: true
  ingress:
    ## @param api.ingress.enabled Whether to enable ingress by creating an Ingress resource. By default, this is disabled. Enabling ingress is advanced usage.
    enabled: true
    ## @param api.ingress.annotations Annotations specified by your ingress controller to customize the behavior of the Ingress resource.
    annotations:
      # kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: local-cluster-issuer
      cert-manager.io/propagation-timeout: "30s"
      cert-manager.io/polling-interval: "5s"
      # kubernetes.io/ingress.class: nginx
    ## @param api.ingress.ingressClassName If implemented by your ingress controller, specifies the ingress class. If your ingress controller does not support this, use the `kubernetes.io/ingress.class` annotation instead.
    ingressClassName: "traefik"
    tls:
      ## @param api.ingress.tls.enabled Whether to associate a certificate with the Ingress resource.
      enabled: true
      ## @param api.ingress.tls.selfSignedCert Whether to generate a self-signed certificate for use with the API server's `Ingress` resource. If `true`, `cert-manager` CRDs **must** be present in the cluster. The chart will create and use its own namespaced `Issuer`. If `false`, a cert `Secret` with the name specified by `api.ingress.tls.secretName` **must** be provided in the same namespace as Kargo. The value in this field has no effect if `api.ingress.tls.enabled` is `false`.
      selfSignedCert: false
      ## @param api.ingress.tls.secretName Name of the cert `Secret` for use with the API server's `Ingress` resource. When `api.ingress.tls.selfSignedCert` is `true`, this will be the name of the generated cert `Secret`. When `api.ingress.tls.selfSignedCert` is `false`, a cert `Secret` with this name **must** be provided in the same namespace as Kargo. The value in this field has no effect if `api.ingress.tls.enabled` is `false`.
      secretName: kargo-tls
    ## @param api.ingress.pathType You may want to use `Prefix` for some controllers (like AWS LoadBalancer Ingress controller), which don't support `/` as wildcard path when pathType is set to `ImplementationSpecific`
    pathType: ImplementationSpecific
